# Generated by Django 4.0.4 on 2022-05-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('age', models.IntegerField(blank=True, verbose_name='Возраст')),
                ('salary', models.IntegerField(blank=True, default=20000, verbose_name='Зарплата')),
                ('skill', models.IntegerField(blank=True, verbose_name='Опыт работы')),
                ('image', models.ImageField(blank=True, upload_to='image/%Y/%m/%d', verbose_name='Фотки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('public', models.BooleanField(default=True, verbose_name='Опубликованно')),
            ],
        ),
    ]
